{!! '<?php' !!}
/**
 * Generated by the control panel — do not edit by hand.
 */

// Encrypts the cookie holding each user's database credentials. Generated for
// this installation: a value shared between installs would let anyone holding
// it decrypt sessions on all of them.
$cfg['blowfish_secret'] = sodium_hex2bin('{{ $blowfishSecret }}');

$i = 0;

$i++;
$cfg['Servers'][$i]['host'] = '{{ $host }}';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;

// Each user signs in with their own database credentials. The alternative
// ('config') means writing a database password into this file, which upstream
// warns against and which would give every visitor of this URL that account.
$cfg['Servers'][$i]['auth_type'] = 'cookie';

// Outside the document root: uploads and exports land here, and anything
// under the web root is a URL somebody can fetch.
$cfg['TempDir'] = '{{ $tempDir }}';
