{!! '<?php' !!}
/**
 * Generated by the control panel — do not edit by hand.
 *
 * Turns a one-time token minted by the panel into a phpMyAdmin signon session.
 *
 * The panel cannot log a user in directly: it runs as its own account, in its
 * own Laravel application, and phpMyAdmin only trusts a PHP session written on
 * this site. So the panel drops a short-lived file that only this site's user
 * can read, and hands the browser a token naming it. Nothing sensitive travels
 * in the URL, and nothing is left on disk once it has been used.
 *
 * Deliberately dependency-free: it is a plain PHP file in a public web root,
 * so the less it does the smaller it is to get wrong.
 */

declare(strict_types=1);

const TOKEN_DIRECTORY = {!! var_export($tokenDirectory, true) !!};
const SIGNON_SESSION = {!! var_export($signonSession, true) !!};
const SIGNON_SERVER = {{ (int) $signonServer }};

/**
 * One answer for every failure. Distinguishing "no such token" from "expired"
 * from "malformed" tells someone guessing tokens which of their guesses was
 * closer, and tells a legitimate user nothing they can act on.
 */
function deny(): never
{
    http_response_code(403);
    header('Content-Type: text/plain; charset=utf-8');
    exit("This sign-in link is not valid. Open phpMyAdmin from the control panel again.\n");
}

$token = isset($_GET['token']) && is_string($_GET['token']) ? $_GET['token'] : '';

/*
 * No token at all is not an attack: phpMyAdmin sends anyone who reaches the
 * signon server without a session straight here, via SignonURL. Send them to
 * the ordinary login form rather than a 403 they cannot do anything about.
 */
if ($token === '') {
    header('Location: /index.php?server=1');
    exit;
}

/*
 * Checked before the token is used to build a path. The token names a file, so
 * without this a crafted value walks out of the directory.
 */
if (preg_match('/^[A-Za-z0-9]{64}$/', $token) !== 1) {
    deny();
}

$file = TOKEN_DIRECTORY.'/'.$token.'.json';

$raw = @file_get_contents($file);

/*
 * Consumed before it is trusted, and a failure to consume it is fatal. If the
 * file cannot be removed the token stays usable for the rest of its life, and
 * a link that has already been used would work again for anyone who has it —
 * so this fails loudly rather than quietly becoming replayable.
 */
$consumed = is_string($raw) && @unlink($file);

if (! $consumed) {
    deny();
}

$payload = json_decode($raw, true);

if (! is_array($payload)
    || ! isset($payload['username'], $payload['password'], $payload['expires_at'])
    || ! is_string($payload['username'])
    || ! is_string($payload['password'])
) {
    deny();
}

if ((int) $payload['expires_at'] < time()) {
    deny();
}

/*
 * Must match $cfg['Servers'][$i]['SignonCookieParams'] in config.inc.php, or
 * phpMyAdmin looks for this session under a cookie that was never set.
 * `secure` follows the request rather than a value fixed at install time: this
 * site starts life on plain HTTP and gains a certificate later, and a cookie
 * marked secure on HTTP is simply never sent.
 */
session_set_cookie_params([
    'lifetime' => 0,
    'path' => '/',
    'secure' => ! empty($_SERVER['HTTPS']),
    'httponly' => true,
    'samesite' => 'Lax',
]);
session_name(SIGNON_SESSION);
session_start();

/* A session id that predates the login must not survive it. */
session_regenerate_id(true);

$_SESSION['PMA_single_signon_user'] = $payload['username'];
$_SESSION['PMA_single_signon_password'] = $payload['password'];
$_SESSION['PMA_single_signon_HMAC_secret'] = bin2hex(random_bytes(20));

session_write_close();

$location = '/index.php?server='.SIGNON_SERVER;

/*
 * Opens on the database the user clicked, when there is one. Passed in the URL
 * rather than through the server's `only_db` — restricting the connection to a
 * single database would also hide every other database the account can legally
 * see, which is not what "open this one" means.
 */
if (isset($payload['database']) && is_string($payload['database']) && $payload['database'] !== '') {
    $location .= '&db='.rawurlencode($payload['database']);
}

header('Location: '.$location);
exit;
