<?php

namespace App\Http\Controllers\API\Server;

use App\Actions\Server\Application\UpdateApplicationBotBlocker;
use App\Enums\AiBotPolicy;
use App\Http\Controllers\Controller;
use App\Http\Requests\Server\Application\UpdateBotBlockerRequest;
use App\Http\Resources\ApplicationResource;
use App\Models\Application;
use Illuminate\Http\JsonResponse;

class ApplicationBotBlockerController extends Controller
{
    /**
     * The three choices and exactly which bots each one blocks — resolved
     * server-side from `config/ai_bots.php` so the frontend never carries its
     * own copy of the bot list to drift out of sync with the one that's
     * actually enforced.
     */
    public function policies(): JsonResponse
    {
        return response()->json([
            'ai_bot_policies' => collect(AiBotPolicy::cases())->mapWithKeys(fn (AiBotPolicy $policy) => [
                $policy->value => [
                    'title' => $policy->title(),
                    'description' => $policy->description(),
                    'blocked_bots' => $policy->blockedBots(),
                    'blocked_count' => count($policy->blockedBots()),
                    // Whether the robots.txt lines below also apply: every
                    // policy that blocks training bots.
                    'robots_txt_recommended' => $policy !== AiBotPolicy::AllowAll,
                ],
            ]),
            // Google and Apple train on what Googlebot and Applebot fetch; the
            // only opt-out is a robots.txt token, which no user-agent rule can
            // match. Given to the owner to add, not written by the panel: the
            // site's robots.txt is often generated by the CMS or an SEO plugin.
            'robots_txt' => [
                'note' => __('app_bot_blocker.robots_txt.note'),
                'lines' => collect((array) config('ai_bots.robots_only'))
                    ->map(fn (string $token): string => "User-agent: {$token}\nDisallow: /")
                    ->implode("\n\n")."\n",
            ],
        ]);
    }

    public function update(UpdateBotBlockerRequest $request, Application $application, UpdateApplicationBotBlocker $action): JsonResponse
    {
        $action->execute($application, $request->policy(), $request->blocked(), $request->allowed());

        return response()->json([
            'application' => ApplicationResource::make($application->fresh(['systemUser', 'botRules']))->resolve(),
        ]);
    }
}
