<?php

use App\Exceptions\Server\Application\ProvisioningFailedException;
use App\Models\Application;
use App\Models\ServerCapability;
use App\Models\SystemUser;
use App\Models\User;
use App\Services\Applications\SiteTypeManager;
use App\Services\Server\Applications\ApplicationProvisioner;
use App\Services\Server\Applications\Installers\N8nInstaller;
use App\Services\Server\Applications\Installers\NodeBbInstaller;
use App\Services\Server\Applications\ProcessSupervisor;
use Database\Seeders\PermissionSeeder;
use Illuminate\Support\Facades\Process;

/**
 * The four one-click Node applications.
 *
 * These are the first installers whose result is a *process* rather than a
 * directory, which changes three things that each have their own way of going
 * wrong: the start command has to be written by the panel, the process must
 * not be started before the code exists, and the application must be pointed
 * at the site rather than at the home directory the unit mounts read-only.
 */
beforeEach(function () {
    $this->seed(PermissionSeeder::class);
    $this->admin = User::factory()->admin()->create();
    $this->token = $this->admin->createToken('t')->plainTextToken;

    ServerCapability::query()->delete();
    ServerCapability::query()->create([
        'stack' => 'mern', 'web_server' => 'nginx',
        'capabilities' => ['php' => true, 'node' => true],
        'source' => 'installer', 'verified_at' => now(),
    ]);

    $this->su = SystemUser::create([
        'username' => 'apps', 'home_path' => '/home/apps',
        'shell' => '/bin/bash', 'sudo' => false,
    ]);

    // Laravel's Process fake has no recorder in this version, so collect the
    // commands as they run — several of these assertions are about *order*.
    $this->ran = collect();

    Process::fake(function ($process) {
        test()->ran->push($process);

        return Process::result(output: '');
    });
});

function oneClickApp(string $type, array $settings = []): Application
{
    // `forceCreate`: `slug` is generated by the panel, never accepted from
    // input, so it is not fillable — and paths derive from it.
    return Application::forceCreate([
        'system_user_id' => test()->su->id,
        'name' => ucfirst($type), 'domain' => "{$type}.test",
        // Real applications always carry one, and paths derive from it rather
        // than from the domain — a site keeps its directory when it is renamed.
        'slug' => $type,
        'site_type' => $type, 'serving_profile' => 'node', 'status' => 'pending',
        'web_root' => '/', 'app_port' => 3300, 'node_version' => '22',
        'settings' => $settings,
    ]);
}

/** Every command that ran, as one searchable blob. */
function ranCommands(): string
{
    return test()->ran
        ->map(fn ($process) => is_array($process->command)
            ? implode(' ', $process->command)
            : (string) $process->command)
        ->implode("\n");
}

/** What was piped into the command that wrote `$path`. */
function writtenTo(string $path): ?string
{
    return test()->ran
        ->first(fn ($process) => is_array($process->command)
            && ($process->command[0] ?? '') === 'tee'
            && in_array($path, $process->command, true))
        ?->input;
}

it('offers all four, and says what each one is', function () {
    $catalog = collect(app(SiteTypeManager::class)->catalog())->keyBy('name');

    foreach (['uptimekuma', 'n8n', 'nodered', 'nodebb'] as $type) {
        expect($catalog[$type]['serving_profile'])->toBe('node')
            ->and($catalog[$type]['has_installer'])->toBeTrue()
            // Localized, never a hardcoded English string in the frontend.
            ->and($catalog[$type]['title'])->not->toStartWith('application.');
    }

    // Only NodeBB stores anything outside its own directory.
    expect($catalog['nodebb']['needs_database'])->toBeTrue()
        ->and($catalog['uptimekuma']['needs_database'])->toBeFalse()
        ->and($catalog['n8n']['needs_database'])->toBeFalse()
        ->and($catalog['nodered']['needs_database'])->toBeFalse();
});

it('never asks for a start command — the installer knows it', function () {
    $fields = collect(app(SiteTypeManager::class)->catalog())
        ->whereIn('name', ['uptimekuma', 'n8n', 'nodered', 'nodebb'])
        ->flatMap(fn (array $type) => collect($type['fields'])->pluck('name'));

    expect($fields)->not->toContain('start_command');
});

it('allocates a port even though nothing asked for one', function () {
    // The user never sends a start command for a one-click application — the
    // installer writes it later — so keying allocation on that left these with
    // no port, a unit with no PORT, and a proxy pointed at nothing.
    $this->withHeaders(['Authorization' => 'Bearer '.$this->token])
        ->postJson('/api/applications', [
            'system_user_id' => $this->su->id,
            'name' => 'Status', 'domain' => 'status.test', 'site_type' => 'uptimekuma',
        ])
        ->assertCreated()
        ->assertJsonPath('application.serving_profile', 'node');

    expect(Application::query()->value('app_port'))->toBeGreaterThanOrEqual(3000);
});

it('writes the start command itself, and starts only after installing', function () {
    $app = oneClickApp('uptimekuma');

    app(ApplicationProvisioner::class)->provision($app);

    expect($app->fresh()->start_command)->toBe('node server/server.js');

    $commands = ranCommands();

    // Cloned and built before anything was started — starting first would run
    // the unit against an empty directory.
    expect(strpos($commands, 'npm run setup'))
        ->toBeLessThan(strpos($commands, 'systemctl restart sv-app-'));
});

it('does not start a git application that has no code yet', function () {
    // Its unit is written and enabled, so the port and the boot behaviour are
    // in place — but `node server.js` in an empty directory exits instantly,
    // and a provision that failed on that would report a broken site that is
    // in fact fine, just not deployed.
    $app = oneClickApp('git');
    $app->update(['start_command' => 'node server.js']);

    $steps = app(ApplicationProvisioner::class)->provision($app);

    expect($steps)->toContain('write_unit')
        ->and($steps)->not->toContain('start_app')
        ->and(ranCommands())->toContain('systemctl enable sv-app-')
        ->and(ranCommands())->not->toContain('systemctl restart sv-app-');
});

it('runs every Node command under the version the site pinned', function () {
    app(ApplicationProvisioner::class)->provision(oneClickApp('n8n'));

    // Otherwise npm resolves through its own `#!/usr/bin/env node` shebang and
    // builds against whatever the panel's PATH had, not the version the unit
    // will run.
    expect(ranCommands())->toContain('PATH=/opt/fnm/node-versions/v22')
        ->and(ranCommands())->toContain('runuser -u apps --');
});

it('keeps n8n inside the site, with a key generated before first start', function () {
    $app = oneClickApp('n8n');

    app(ApplicationProvisioner::class)->provision($app);

    // `{home}/{slug}/public_html` — the document root, not a directory named
    // after the domain. Renaming a site must not move its files.
    expect(writtenTo('/home/apps/n8n/public_html/.env'))
        // The home is mounted read-only by the unit, so the default ~/.n8n
        // would start and then fail to write.
        ->toContain('N8N_USER_FOLDER="/home/apps/n8n/public_html"')
        // Reached through the reverse proxy only.
        ->toContain('N8N_LISTEN_ADDRESS="127.0.0.1"')
        ->toContain('N8N_PORT="3300"')
        // Lose this and every stored credential is unreadable, with no error
        // until a workflow runs.
        ->toMatch('/N8N_ENCRYPTION_KEY="[0-9a-f]{64}"/')
        // TLS is optional and is issued only after installation. The
        // certificate lifecycle promotes this once HTTPS is really servable.
        ->toContain('WEBHOOK_URL="http://n8n.test/"');
});

it('restarts n8n when its public URL changes', function () {
    $application = oneClickApp('n8n');
    $application->forceFill([
        'status' => 'active',
        'start_command' => '/home/apps/n8n/public_html/node_modules/.bin/n8n start',
    ])->save();

    app(N8nInstaller::class)->syncUrl($application, 'https://n8n.test');

    expect(ranCommands())->toContain('systemctl restart sv-app-'.$application->id.'.service');
});

it('gives Node-RED a password, because it ships without one', function () {
    // An unauthenticated Node-RED is a remote shell: a flow runs arbitrary
    // code as the site user.
    $app = oneClickApp('nodered', ['admin_username' => 'ops', 'admin_password' => 'a-long-password']);

    app(ApplicationProvisioner::class)->provision($app);

    expect(writtenTo('/home/apps/nodered/public_html/settings.js'))
        ->toContain('username: "ops"')
        // $2a$, not PHP's $2y$: bcryptjs accepts both but the native bcrypt
        // binding rejects $2y$ outright.
        ->toMatch('/password: "\$2a\$/')
        ->toContain('uiPort: process.env.PORT')
        // The default user directory is under the home, which the unit mounts
        // read-only — so a flow could never be saved.
        ->and($app->fresh()->start_command)
        ->toBe('node /home/apps/nodered/public_html/node_modules/node-red/red.js'
            .' --userDir /home/apps/nodered/public_html --settings /home/apps/nodered/public_html/settings.js');
});

it('greys NodeBB on a server with no MongoDB, rather than offering MySQL', function () {
    // No mongo client on this box, which is how the engine reports itself
    // absent.
    Process::fake(fn ($process) => ($process->command[0] ?? '') === 'mongosh'
        ? Process::result(exitCode: 1)
        : Process::result(output: ''));

    $nodebb = collect(app(SiteTypeManager::class)->catalog())->firstWhere('name', 'nodebb');

    // NodeBB speaks MongoDB, Redis or PostgreSQL — never MySQL. Offering the
    // card and then failing inside its setup would send the user to install
    // the one database that cannot help.
    expect($nodebb['available'])->toBeFalse()
        ->and($nodebb['unavailable_reason'])->toContain('MongoDB')
        // Nothing the runtime installer offers would fix this.
        ->and($nodebb['installable_runtime'])->toBeNull();
});

it('starts NodeBB in the foreground, so systemd keeps hold of it', function () {
    $app = oneClickApp('nodebb');
    $installer = app(NodeBbInstaller::class);

    // Without --no-daemon the loader forks and exits; systemd sees the parent
    // die and kills the children it left behind in the cgroup.
    expect($installer->startCommand($app, '/home/apps/nodebb/public_html'))
        ->toBe('node /home/apps/nodebb/public_html/loader.js --no-daemon --no-silent')
        ->and($installer->acceptedEngines())->toBe(['mongodb']);
});

describe('NodeBB asset build', function () {
    it('builds the assets after writing the final config, and checks the result', function () {
        $app = oneClickApp('nodebb');
        $root = '/home/apps/nodebb/public_html';

        // `cat config.json` has to answer with what setup wrote, because the
        // installer now *patches* that file rather than overwriting it — the
        // whole point being that setup's own keys survive.
        Process::fake(function ($process) {
            test()->ran->push($process);
            $command = implode(' ', (array) $process->command);

            if (str_contains($command, 'cat ') && str_contains($command, 'config.json')) {
                return Process::result(output: json_encode([
                    'url' => 'http://old.example', 'port' => 4567,
                    'database' => 'mongo',
                    // The key setup owns and the panel must not destroy.
                    'mongo' => ['host' => '127.0.0.1', 'database' => 'nodebb'],
                ]));
            }

            return str_contains($command, '-name *.tpl')
                ? Process::result(output: '/home/apps/nodebb/public_html/build/public/templates/categories.tpl')
                : Process::result(output: '');
        });

        app(NodeBbInstaller::class)->install($app, $root, [
            'db_host' => '127.0.0.1', 'db_port' => 27017,
            'db_user' => 'nodebb', 'db_password' => 'secret', 'database' => 'nodebb',
        ]);

        $commands = test()->ran
            ->map(fn ($process) => implode(' ', (array) $process->command))
            ->values();

        $build = $commands->search(fn (string $c) => str_contains($c, './nodebb build'));

        // `setup` builds too, so the temptation is to call this redundant —
        // and leaving it out is what produced a forum that installed cleanly
        // and then answered "Failed to lookup view! Did you run `./nodebb
        // build`?" on every request. setup's build can fail without failing
        // setup; this one's exit code is checked.
        expect($build)->not->toBeFalse();

        // After the config rewrite, not before: the build has to see the URL
        // and port the panel gave the site, not the ones setup left behind.
        $lastConfigWrite = $commands->reduce(
            fn (?int $carry, string $c, int $i) => str_contains($c, 'config.json') ? $i : $carry,
            null,
        );

        expect($lastConfigWrite)->not->toBeNull()
            ->and($build)->toBeGreaterThan($lastConfigWrite);
    });

    it('patches the config setup wrote instead of replacing it', function () {
        $app = oneClickApp('nodebb');

        Process::fake(function ($process) {
            test()->ran->push($process);
            $command = implode(' ', (array) $process->command);

            if (str_contains($command, 'cat ') && str_contains($command, 'config.json')) {
                return Process::result(output: json_encode([
                    'url' => 'http://old.example',
                    'database' => 'mongo',
                    // Written by `./nodebb setup`, not by this installer. The
                    // old code replaced the file with its own six keys and
                    // discarded anything like this — and `./nodebb build` reads
                    // this file to reach the database and find the active
                    // theme, then compiles nothing and still exits 0.
                    'setup_only_key' => 'must survive',
                ]));
            }

            return str_contains($command, '-name *.tpl')
                ? Process::result(output: '/x/categories.tpl')
                : Process::result(output: '');
        });

        app(NodeBbInstaller::class)->install($app, '/home/apps/nodebb/public_html', [
            'db_host' => '127.0.0.1', 'db_port' => 27017,
            'db_user' => 'nodebb', 'db_password' => 'secret', 'database' => 'nodebb',
        ]);

        // The *last* config write, not the first: one goes in before setup,
        // and it is the one after setup that used to destroy setup's keys.
        $written = test()->ran
            ->map(fn ($p) => (string) $p->input)
            ->filter(fn (string $i) => str_contains($i, '"url"'))
            ->last();

        expect($written)->toContain('setup_only_key')
            ->and($written)->toContain('must survive')
            // and the panel's own values still land
            ->and($written)->toContain('nodebb.test');
    });

    it('fails provisioning when the build claims success but compiles nothing', function () {
        $app = oneClickApp('nodebb');

        // The reported failure, exactly: a forum created *after* the build step
        // was added still answered "Failed to lookup view!" on every request,
        // with nothing wrong anywhere in provisioning. `./nodebb build` exits 0
        // having compiled no templates, so the exit code is not the evidence —
        // the artifact is.
        Process::fake(function ($process) {
            test()->ran->push($process);
            $command = implode(' ', (array) $process->command);

            if (str_contains($command, 'cat ') && str_contains($command, 'config.json')) {
                return Process::result(output: json_encode(['url' => 'http://old.example', 'database' => 'mongo']));
            }

            // Everything succeeds, including the build. The templates
            // directory is simply empty.
            return Process::result(output: '');
        });

        expect(fn () => app(NodeBbInstaller::class)->install($app, '/home/apps/nodebb/public_html', [
            'db_host' => '127.0.0.1', 'db_port' => 27017,
            'db_user' => 'nodebb', 'db_password' => 'secret', 'database' => 'nodebb',
        ]))->toThrow(ProvisioningFailedException::class);
    });

    it('fails provisioning when the build fails, rather than serving a broken forum', function () {
        $app = oneClickApp('nodebb');

        // The build dying on a small box is the common case — it runs its
        // targets in parallel and exhausts the RAM. Silence here is what put
        // a 500 on every page instead of an error on the install screen.
        Process::fake(function ($process) {
            test()->ran->push($process);

            return str_contains(implode(' ', (array) $process->command), './nodebb build')
                ? Process::result(exitCode: 1, errorOutput: 'FATAL ERROR: heap out of memory')
                : Process::result(output: '');
        });

        expect(fn () => app(NodeBbInstaller::class)->install($app, '/home/apps/nodebb/public_html', [
            'db_host' => '127.0.0.1', 'db_port' => 27017,
            'db_user' => 'nodebb', 'db_password' => 'secret', 'database' => 'nodebb',
        ]))->toThrow(ProvisioningFailedException::class);
    });
});

describe('unit memory ceiling', function () {
    it('gives an application what it needs rather than one server-wide number', function () {
        // 512M was applied to every Node app regardless of what it was.
        // MemoryMax kills rather than throttles, so an app under its own
        // documented minimum is not slow — it is killed at startup, restarts
        // to its start limit, stops, and the site answers 502 while the panel
        // reports it active.
        config(['server.applications.memory_max' => '512M']);

        $supervisor = app(ProcessSupervisor::class);

        $n8n = oneClickApp('n8n');
        $n8n->start_command = 'node x.js';
        $supervisor->apply($n8n, '/home/apps/n8n/public_html', start: false);

        $unit = test()->ran
            ->map(fn ($p) => (string) $p->input)
            ->first(fn (string $i) => str_contains($i, 'MemoryMax='));

        // n8n's own docs ask for 2 GB.
        expect($unit)->toContain('MemoryMax=2G');
    });

    it('falls back to the server default for a type with no opinion', function () {
        config(['server.applications.memory_max' => '512M']);

        $app = oneClickApp('nodered');
        $app->start_command = 'node x.js';
        app(ProcessSupervisor::class)
            ->apply($app, '/home/apps/nodered/public_html', start: false);

        $unit = test()->ran
            ->map(fn ($p) => (string) $p->input)
            ->first(fn (string $i) => str_contains($i, 'MemoryMax='));

        expect($unit)->toContain('MemoryMax=512M');
    });
});
