{!! '<?php' !!}
/**
 * Generated by the control panel. Holds live database credentials — keep it 0640.
 *
 * Written rather than left to Moodle's installer so that the database
 * password never appears on a command line, where `ps` would show it to every
 * user on the machine.
 */

unset($CFG);
global $CFG;
$CFG = new stdClass();

$CFG->dbtype    = '{{ $dbType }}';
$CFG->dblibrary = 'native';
$CFG->dbhost    = '{{ $host }}';
$CFG->dbname    = '{{ $database }}';
$CFG->dbuser    = '{{ $username }}';
$CFG->dbpass    = '{{ $password }}';
$CFG->prefix    = '{{ $prefix }}';
$CFG->dboptions = [
    'dbpersist' => 0,
    'dbport' => '',
    'dbsocket' => '',
    'dbcollation' => 'utf8mb4_unicode_ci',
];

$CFG->wwwroot   = '{{ $wwwroot }}';
$CFG->dataroot  = '{{ $dataroot }}';
$CFG->admin     = 'admin';

// Moodle's own example uses 0777. The site runs as its own user here, so
// nothing outside it needs access to what students upload.
$CFG->directorypermissions = 0750;

require_once(__DIR__ . '/lib/setup.php');
