"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { toast } from "sonner";
import { KeyRound, Loader2 } from "lucide-react";
import {
  acknowledgeContainerSecrets,
  getContainerSecrets,
} from "@/lib/api/docker";
import { apiMessage } from "@/lib/api/error-message";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { CopyButton } from "@/components/ui/copy-button";
import { Caution } from "@/components/ui/caution";

/**
 * The credentials a one-click app generated, shown once, where the user lands.
 *
 * **Why this exists.** A container app's admin password is generated by the panel —
 * Grafana's is the clearest case — and the only way to it was a Reveal button on the
 * Container screen, two clicks into a site, which nobody thinks to look for on the
 * day they install something. A password generated and never shown is the same as an
 * account nobody can sign into.
 *
 * **Shown, not hidden behind a button, and that is the difference from
 * `ContainerCredentials`.** There the values are masked until asked for, because that
 * screen is somewhere you go back to and a password on a page you visit for other
 * reasons is a password on a shoulder-surfed screen. Here the entire purpose is that
 * the first view happens, so it fetches on mount.
 *
 * **Dismissed only by the button.** The values cannot be rotated from the panel —
 * changing one means rewriting the compose file AND the credential inside the running
 * database — so a card that disappeared on its own would lose something
 * unrecoverable to a stray refresh. It stays until somebody says they have them, and
 * it stays across reloads because that answer is a column on the site, not state in
 * this component.
 *
 * Nothing is lost by dismissing: the same values remain under Container → Reveal.
 */
export function FirstRunCredentials({ application, className }) {
  const t = useTranslations("applications.container.firstRun");
  const router = useRouter();
  const [secrets, setSecrets] = useState(null);
  const [error, setError] = useState(null);
  const [saving, setSaving] = useState(false);

  const keys = application.container_secret_keys ?? [];

  useEffect(() => {
    let cancelled = false;

    async function load() {
      try {
        const { data } = await getContainerSecrets(application.id);
        if (!cancelled) setSecrets(data?.secrets ?? {});
      } catch (requestError) {
        // Shown rather than swallowed. A card that promises credentials and
        // renders nothing is worse than no card — the user has no way to tell
        // "still loading" from "there are none" from "the request failed", and
        // the one thing they must not conclude is that there was nothing to save.
        if (!cancelled) setError(apiMessage(requestError, t("failed")));
      }
    }

    load();

    return () => {
      cancelled = true;
    };
  }, [application.id, t]);

  async function acknowledge() {
    setSaving(true);
    try {
      await acknowledgeContainerSecrets(application.id);
      // The card's visibility comes from a server-rendered field, so without this
      // it would sit there after a successful dismiss until the next navigation.
      router.refresh();
    } catch (requestError) {
      toast.error(apiMessage(requestError, t("acknowledgeFailed")));
    } finally {
      setSaving(false);
    }
  }

  if (keys.length === 0) return null;

  return (
    <Card className={className}>
      <CardHeader>
        <CardTitle
          as="h2"
          className="flex items-center gap-2"
        >
          {t("title")}
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <Caution size="md" icon={KeyRound}>
          <p>{t("body")}</p>
        </Caution>

        {error ? (
          <Caution size="md" tone="destructive">
            <p>{error}</p>
          </Caution>
        ) : (
          <ul className="divide-y rounded-lg border">
            {keys.map((key) => (
              <li
                key={key}
                className="flex items-center justify-between gap-3 px-3 py-2"
              >
                <span className="min-w-0 truncate font-mono text-xs text-muted-foreground">
                  {key}
                </span>
                {secrets ? (
                  <span className="flex min-w-0 items-center gap-1.5">
                    {/* Not truncated. A password clipped to fit is a password
                        somebody transcribes wrongly, and this card exists for
                        exactly the one reading where that matters. */}
                    <code className="min-w-0 break-all font-mono text-xs">
                      {secrets[key]}
                    </code>
                    <CopyButton value={secrets[key] ?? ""} />
                  </span>
                ) : (
                  <Loader2
                    className="size-3.5 shrink-0 animate-spin text-muted-foreground"
                    aria-label={t("loading")}
                  />
                )}
              </li>
            ))}
          </ul>
        )}

        {/* Enabled only once the values are on screen. A dismiss button beside a
            row of spinners invites the one click that cannot be undone. */}
        <div className="flex flex-wrap items-center gap-3">
          <Button
            onClick={acknowledge}
            disabled={saving || !secrets}
            disabledReason={!secrets ? t("valuesNotShown") : null}
          >
            {saving ? <Loader2 className="size-3.5 animate-spin" /> : null}
            {t("acknowledge")}
          </Button>
          <p className="text-xs text-muted-foreground">{t("laterHint")}</p>
        </div>
      </CardContent>
    </Card>
  );
}
