{!! '<?php' !!}
/**
 * Generated by the panel. Holds live database credentials — keep it 0640.
 */

define('DB_NAME', '{{ $database }}');
define('DB_USER', '{{ $username }}');
define('DB_PASSWORD', '{{ $password }}');
define('DB_HOST', '{{ $host }}');
define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATE', '');

{{-- Unique per install: shared salts would let a leak on one site forge
     sessions on another. --}}
@foreach ($salts as $name => $value)
define('{{ $name }}', '{{ $value }}');
@endforeach

$table_prefix = '{{ $prefix }}';

define('WP_DEBUG', false);
define('DISALLOW_FILE_EDIT', true);

{{-- Staging-only, all null/false on a normal install so this changes nothing
     for it. `WP_HOME`/`WP_SITEURL` pin the site to its own domain regardless
     of what got copied into the database; `DISABLE_WP_CRON` is the one
     non-negotiable staging safeguard — without it, scheduled tasks a clone
     inherited (WooCommerce emails, drip campaigns) fire against real
     customers from a site nobody is meant to be treating as live. --}}
@if ($home ?? null)
define('WP_HOME', '{{ $home }}');
define('WP_SITEURL', '{{ $siteUrl ?? $home }}');
@endif
@if ($environmentType ?? null)
define('WP_ENVIRONMENT_TYPE', '{{ $environmentType }}');
@endif
@if ($disableCron ?? false)
define('DISABLE_WP_CRON', true);
@endif

if (! defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}

require_once ABSPATH . 'wp-settings.php';
