&lt;?php
/**
 * Generated by the panel. Holds live database credentials — keep it 0640.
 */

define('DB_NAME', '{{ $database }}');
define('DB_USER', '{{ $username }}');
define('DB_PASSWORD', '{{ $password }}');
define('DB_HOST', '{{ $host }}');
define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATE', '');

{{-- Unique per install: shared salts would let a leak on one site forge
     sessions on another. --}}
@foreach ($salts as $name => $value)
define('{{ $name }}', '{{ $value }}');
@endforeach

$table_prefix = '{{ $prefix }}';

define('WP_DEBUG', false);
define('DISALLOW_FILE_EDIT', true);

if (! defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}

require_once ABSPATH . 'wp-settings.php';
