# Generated by the control panel. Holds live credentials — keep it 0640.
#
# Craft reads its database settings from here, which is what keeps them off
# any command line.

CRAFT_APP_ID={{ $appId }}
CRAFT_ENVIRONMENT=production
CRAFT_SECURITY_KEY={{ $securityKey }}

CRAFT_DB_DRIVER={{ $driver }}
CRAFT_DB_SERVER={{ $host }}
CRAFT_DB_PORT={{ $port }}
CRAFT_DB_DATABASE={{ $database }}
CRAFT_DB_USER={{ $username }}
CRAFT_DB_PASSWORD={{ $password }}
CRAFT_DB_SCHEMA=public
CRAFT_DB_TABLE_PREFIX=

PRIMARY_SITE_URL={{ $siteUrl }}
DEV_MODE=false
ALLOW_ADMIN_CHANGES=false
DISALLOW_ROBOTS=false
