{!! '<?php' !!}
/**
 * Generated by the control panel. Holds live credentials — keep it 0640.
 *
 * This is the pre-install configuration Mautic merges before applying CLI
 * options. `site_url` must stay absent until Mautic's final installation step:
 * together with db_driver it is Mautic's own "already installed" marker.
 */

$parameters = {!! var_export($parameters, true) !!};
