{!! '<?php' !!}
/**
 * Generated by ServerAvatar OSS. Holds live credentials — keep it 0640.
 *
 * Mautic's installer merges these before applying command-line options, which
 * is what lets the install run with no secret on the command line at all.
 */

$parameters = [
    'db_driver' => 'pdo_mysql',
    'db_host' => '{{ $host }}',
    'db_port' => '{{ $port }}',
    'db_name' => '{{ $database }}',
    'db_user' => '{{ $username }}',
    'db_password' => '{{ $password }}',
    'db_table_prefix' => null,
    'db_backup_tables' => false,

    'admin_email' => '{{ $adminEmail }}',
    'admin_username' => '{{ $adminUsername }}',
    'admin_password' => '{{ $adminPassword }}',
    'admin_firstname' => '{{ $adminFirstName }}',
    'admin_lastname' => '{{ $adminLastName }}',

    'site_url' => '{{ $siteUrl }}',
];
