/**
 * Sample applications behind `?preview=` on the real Applications pages, so the
 * list and the detail screen can be reviewed while creating one is blocked on
 * the server side. Shapes match `applicationSchema` exactly — a fixture that
 * drifts from the schema previews a screen that cannot exist.
 *
 * Delete this file and the `preview` branches in the two pages once real
 * applications can be created.
 */

export const previewApplications = [
  {
    id: 104,
    name: "Docs",
    domain: "docs.example.com",
    site_type: "static",
    site_type_title: "Static site",
    serving_profile: "static",
    rendering_type: null,
    status: "pending",
    status_title: "Pending",
    deployed: false,
    system_user: { id: 12, username: "shop" },
    php_version: null,
    node_version: null,
    app_port: null,
    web_root: "/home/shop/docs.example.com/public",
    build_command: null,
    start_command: null,
    git_account_id: null,
    repository: null,
    repository_url: null,
    branch: null,
    settings: {},
    steps: [],
    failed_step: null,
    reference: null,
    created_at: "04-08-2026 05:12:40",
    created_at_human: "a few seconds ago",
  },
  {
    id: 103,
    name: "Billing API",
    domain: "api.example.com",
    site_type: "laravel",
    site_type_title: "Laravel",
    serving_profile: "php",
    rendering_type: null,
    status: "provisioning",
    status_title: "Provisioning",
    deployed: false,
    system_user: { id: 13, username: "billing" },
    php_version: "8.4",
    node_version: null,
    app_port: null,
    web_root: "/home/billing/api.example.com/public",
    build_command: "composer install --no-dev",
    start_command: null,
    git_account_id: 3,
    repository: "acme/billing-api",
    repository_url: "https://github.com/acme/billing-api",
    branch: "main",
    settings: {},
    steps: ["System user checked", "Directories created", "Repository cloned"],
    failed_step: null,
    reference: null,
    created_at: "04-08-2026 05:09:18",
    created_at_human: "3 minutes ago",
  },
  {
    id: 105,
    name: "Legacy Shop",
    domain: "legacy.example.com",
    site_type: "wordpress",
    site_type_title: "WordPress",
    serving_profile: "php",
    rendering_type: null,
    status: "failed",
    status_title: "Failed",
    deployed: false,
    system_user: { id: 14, username: "legacy" },
    php_version: "8.2",
    node_version: null,
    app_port: null,
    web_root: "/home/legacy/legacy.example.com/public",
    build_command: null,
    start_command: null,
    git_account_id: null,
    repository: null,
    repository_url: null,
    branch: null,
    settings: {},
    steps: ["System user checked", "Directories created"],
    failed_step: "Database creation",
    reference: "3f2b71ac-0c4d-4f1e-9a55-1e0b6c2f77aa",
    created_at: "02-08-2026 16:41:02",
    created_at_human: "2 days ago",
  },
  {
    id: 102,
    name: "Storefront",
    domain: "shop.example.com",
    site_type: "nextjs",
    site_type_title: "Next.js",
    serving_profile: "node",
    rendering_type: "ssr",
    status: "active",
    status_title: "Active",
    deployed: true,
    system_user: { id: 12, username: "shop" },
    php_version: null,
    node_version: "22",
    app_port: 3000,
    web_root: "/home/shop/shop.example.com",
    build_command: "npm run build",
    start_command: "npm run start",
    git_account_id: 3,
    repository: "acme/storefront",
    repository_url: "https://github.com/acme/storefront",
    branch: "main",
    settings: {},
    has_process: true,
    process: {
      state: "active",
      sub_state: "running",
      since: "21-07-2026 11:09:41",
      memory: "148 MB",
      restarts: 0,
    },
    webhook: {
      enabled: true,
      provider: "github",
      verification: "signature",
      last_delivered_at_human: "2 days ago",
    },
    last_commit: "9f2c1a4e77b3d0c5aa18",
    last_deployed_at: "02-08-2026 09:22:10",
    last_deployed_at_human: "2 days ago",
    steps: [
      "System user checked",
      "Directories created",
      "Repository cloned",
      "Dependencies installed",
      "Service started",
    ],
    failed_step: null,
    reference: null,
    created_at: "21-07-2026 11:05:33",
    created_at_human: "2 weeks ago",
  },
  {
    id: 101,
    name: "Company Blog",
    domain: "blog.example.com",
    site_type: "wordpress",
    site_type_title: "WordPress",
    serving_profile: "php",
    rendering_type: null,
    status: "active",
    status_title: "Active",
    deployed: true,
    system_user: { id: 11, username: "blog" },
    php_version: "8.3",
    node_version: null,
    app_port: null,
    web_root: "/home/blog/blog.example.com/public",
    build_command: null,
    start_command: null,
    git_account_id: null,
    repository: null,
    repository_url: null,
    branch: null,
    settings: {},
    steps: [
      "System user checked",
      "Directories created",
      "WordPress downloaded",
      "Database created",
      "Site configured",
    ],
    failed_step: null,
    reference: null,
    created_at: "12-07-2026 08:47:19",
    created_at_human: "3 weeks ago",
  },
];

// Built from the application's own domain — a fixed list showed every site the
// blog's hostname, which is exactly the kind of lie a preview must not tell.
// One primary, one alias, one redirect, so the counts have something to say.
export function previewDomainsFor(application) {
  const domain = application?.domain ?? "example.com";
  return [
    { id: 1, domain, type: "primary", dns_verified: true, certifiable: true },
    { id: 2, domain: `www.${domain}`, type: "alias", dns_verified: true, certifiable: true },
    {
      id: 3,
      domain: `old-${domain}`,
      type: "redirect",
      redirect_to: `https://${domain}`,
      redirect_status: 301,
      dns_verified: true,
      certifiable: true,
    },
  ];
}

export function previewCertificateFor(application) {
  const domain = application?.domain ?? "example.com";
  return {
    id: 1,
    type: "letsencrypt",
    type_title: "Let's Encrypt",
    status: "active",
    domains: [domain, `www.${domain}`],
    missing_domains: [],
    force_https: true,
    auto_renew: true,
    renewable: true,
    expires_at: "22-10-2026 08:47:19",
    expires_at_human: "in 3 months",
    days_remaining: 79,
    expired: false,
    expiring_soon: false,
  };
}

export function findPreviewApplication(id) {
  return previewApplications.find((application) => String(application.id) === String(id)) ?? null;
}
